version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 5001:5001
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    ports:
      - 5437:5432
    env_file:
      - .env
    volumes:
      - ./database/data:/var/lib/postgresql/data
    restart: unless-stopped
# create a container for the database backup
